#    _______        _                   ____  _            _
#   |__   __|      | |                 |  _ \| |          | |
#      | | ___  ___| |__  _ __   ___   | |_) | | ___   ___| | _____
#      | |/ _ \/ __| '_ \| '_ \ / _ \  |  _ <| |/ _ \ / __| |/ / __|
#      | |  __/ (__| | | | | | | (_) | | |_) | | (_) | (__|   <\__ \
#      |_|\___|\___|_| |_|_| |_|\___/  |____/|_|\___/ \___|_|\_\___/
#                Version: 2.0 Developed by TechnoAde#2952

config-version: 1

itemselector:
  position: 8
  displayname: "&4ciccio"

ciccio:
  1:
    "adad"
  2:
    "adad"